config/routes.rb
Rails.application.routes.draw do

  resources :invoices

  resources :workers

  resources :appointment_statuses

  resources :diagnostics

  resources :patients

  resources :appointments

  resources :dermatologists

  resources :users

 root :to => 'users#index'

end

app/models/dermatologist.rb
class Dermatologist < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments
  has_many :invoices, :through => :appointments
end

app/controllers/dermatologists_controller.rb
class DermatologistsController < ApplicationController
  before_action :set_dermatologist, only: [:show, :edit, :update, :destroy]

  # GET /dermatologists
  # GET /dermatologists.json
  def index
    @dermatologists = Dermatologist.all
  end

  # GET /dermatologists/1
  # GET /dermatologists/1.json
  def show
  end

  # GET /dermatologists/new
  def new
    @dermatologist = Dermatologist.new
  end

  # GET /dermatologists/1/edit
  def edit
  end

  # POST /dermatologists
  # POST /dermatologists.json
  def create
    @dermatologist = Dermatologist.new(dermatologist_params)

    respond_to do |format|
      if @dermatologist.save
        format.html { redirect_to @dermatologist, notice: 'Dermatologist was successfully created.' }
        format.json { render :show, status: :created, location: @dermatologist }
      else
        format.html { render :new }
        format.json { render json: @dermatologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dermatologists/1
  # PATCH/PUT /dermatologists/1.json
  def update
    respond_to do |format|
      if @dermatologist.update(dermatologist_params)
        format.html { redirect_to @dermatologist, notice: 'Dermatologist was successfully updated.' }
        format.json { render :show, status: :ok, location: @dermatologist }
      else
        format.html { render :edit }
        format.json { render json: @dermatologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dermatologists/1
  # DELETE /dermatologists/1.json
  def destroy
    @dermatologist.destroy
    respond_to do |format|
      format.html { redirect_to dermatologists_url, notice: 'Dermatologist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dermatologist
      @dermatologist = Dermatologist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dermatologist_params
      params.require(:dermatologist).permit(:name, :diagnostic_code)
    end
end

app/helpers/dermatologists_helper.rb
module DermatologistsHelper
end

app/views/dermatologists/_form.html.erb
<%= form_for(@dermatologist) do |f| %>
  <% if @dermatologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dermatologist.errors.count, "error") %> prohibited this dermatologist from being saved:</h2>

      <ul>
      <% @dermatologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dermatologists/edit.html.erb
<h1>Editing dermatologist</h1>

<%= render 'form' %>

<%= link_to 'Show', @dermatologist %> |
<%= link_to 'Back', dermatologists_path %>

app/views/dermatologists/index.html.erb
<h3>Dermatologists</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>

           <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dermatologists.each do |dermatologist| %>
      <tr>
        <td><%= dermatologist.name %></td>
        <td><%= link_to 'Show', dermatologist %></td>
        <td><%= link_to 'Edit', edit_dermatologist_path(dermatologist) %></td>
          </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Dermatologist', new_dermatologist_path %>

<br>

</tr>

<br>

<%= link_to 'Diagnostic Code Link', 'http://www.dermadvocate.net/library/articles/dermatology-icd-9-codes-new' %>
<br>
<td>
  <br>

</td>
<%= link_to 'Diagnostic Codes', diagnostics_path %>

app/views/dermatologists/new.html.erb
<h3>New Dermatologist</h3>

<%= render 'form' %>

<%= link_to 'Back', dermatologists_path %>

app/views/dermatologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dermatologist.name %>
</p>


<%= link_to 'Edit', edit_dermatologist_path(@dermatologist) %> |
<%= link_to 'Back', dermatologists_path %>