config/routes.rb
Rails.application.routes.draw do

  resources :invoices

  resources :workers

  resources :appointment_statuses

  resources :diagnostics

  resources :patients

  resources :appointments

  resources :dermatologists

  resources :users

 root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Patient, :Dermatologist, :Office_Worker, :Admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Patients %><br>
    <%= f.link :Patients %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h3>  Welcome to Dermatologists R Us !</h3>

<br>


<h4> If you are a new patient please click the link below </h4>
  <br>




<table>
  <thead>
    <tr>
         <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>



      <tr>

         </tr>

  </tbody>


</table>

<br>

 <%= link_to 'Patient', new_patient_path %>
  </tbody>


  <br>

  <h4> To cancel and appointment click here </h4>

<td><%= link_to 'Appointments',  appointments_path  %></td>

app/views/users/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patients:</strong>
  <%= @user.Patients %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>